version: '3.7'
services:
  flexget:
    image: madwind/flexget
    container_name: flexget
    environment:
      FG_WEBUI_PASSWD: 12nfo34ivc043iv9
      FG_LOG_LEVEL: INFO
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
    volumes:
      - <path for config files>:/config
      - <path for data files>:/downloads
    ports:
      - "3539:3539"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
